name: Compile Game
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Test-Build-Game:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: curl -LO https://github.com/libsdl-org/SDL/releases/download/release-2.30.8/SDL2-devel-2.30.8-mingw.zip
      - run: curl -LO https://github.com/libsdl-org/SDL_image/releases/download/release-2.8.2/SDL2_image-devel-2.8.2-mingw.zip 
      - run: curl -LO  "https://downloads.sourceforge.net/project/mingw-w64/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/8.1.0/threads-win32/seh/x86_64-8.1.0-release-win32-seh-rt_v6-rev0.7z?ts=gAAAAABnBmagDFfAuid5yGUE9nMbUKUq1u7v2WWJYHJJHBSYjswxaxMD1fZSvWAslcj0WwU1Nezr46xR7d5aH_PRXNx6qfXgbg%3D%3D&r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fmingw-w64%2Ffiles%2FToolchains%2520targetting%2520Win64%2FPersonal%2520Builds%2Fmingw-builds%2F8.1.0%2Fthreads-win32%2Fseh%2Fx86_64-8.1.0-release-win32-seh-rt_v6-rev0.7z%2Fdownload%3Fuse_mirror%3Daltushost-swe%26use_mirror%3Daltushost-swe%26r%3Dhttps%253A%252F%252Fwww.youtube.com%252F"
      - run: tar -xf SDL2-devel-2.30.8-mingw.zip
      - run: tar -xf SDL2_image-devel-2.8.2-mingw.zip
      - uses: milliewalky/setup-7-zip@v1
      - run: 7z x x86_64-8.1.0-release-win32-seh-rt_v6-rev0.7z
      - run: rm -r x86_64-8.1.0-release-win32-seh-rt_v6-rev0.7z
      - run: cp SDL2_image-2.8.2\x86_64-w64-mingw32\bin\SDL2_image.dll .\build
      - run: cp SDL2-2.30.8\x86_64-w64-mingw32\bin\SDL2.dll .\build
      # - run: rm -r SDL2-2.30.8 
      # - run: rm -r SDL2_image-2.8.2
      # - run: rm -r SDL2-2.30.8.zip 
      # - run: rm -r SDL2_image-2.8.2.zip
      - run: echo "mingw64\x86_64-w64-mingw32\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - uses: egor-tensin/setup-mingw@v2.2.0
        with:
          version: 12.2.0
          platform: x64
      - shell: powershell
        run: .\pipeline.bat
      - run: rm build\libgcc_s_sjlj-1.dll
      - run: ls ./build
      - uses: actions/upload-artifact@v4
        with:
          name: Game
          path: build
