name: Compile Game
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Test-Build-Game:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: egor-tensin/setup-mingw@v2.2.0
        with:
          version: 12.2.0
          platform: x64
      - run: mkdir ./bin-int/Debug-windows/MainGame
      - run: mkdir ./bin/Debug-windows/MainGame
      - shell: powershell
        run: |
          ./vendor/premake5.exe gmake2
          make
      - name: Copy Dependencies
        run: |
          cp "./SDL2.dll" "./bin/Debug-windows/MainGame"
          cp "./SDL2_image.dll" "./bin/Debug-windows/MainGame"
          mkdir "./bin/Debug-windows/MainGame/sprites"
          cp "./MainGame/sprites" "./bin/Debug-windows/MainGame/sprites" /E /Y
      - run: ls ./bin
      - uses: actions/upload-artifact@v4
        with:
          name: Game
          path: bin
