name: Compile Game
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: curl -LO https://github.com/libsdl-org/SDL/releases/download/release-2.30.8/SDL2-devel-2.30.8-mingw.zip
      - run: curl -LO https://github.com/libsdl-org/SDL_image/releases/download/release-2.8.2/SDL2_image-devel-2.8.2-mingw.zip 
      - run: tar -xf SDL2-devel-2.30.8-mingw.zip
      - run: tar -xf SDL2_image-devel-2.8.2-mingw.zip
      - run: cp SDL2_image-2.8.2\x86_64-w64-mingw32\bin\SDL2_image.dll .\build
      - run: cp SDL2-2.30.8\x86_64-w64-mingw32\bin\SDL2.dll .\build
      - shell: powershell
        run: .\pipeline.bat
      - run: ls ./build
      - uses: actions/upload-artifact@v4
        with:
          name: Game
          path: build
